name: Build on Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: Invoke-WebRequest -Uri "https://web.archive.org/web/20060114221019if_/http://community.borland.com:80/article/images/21751/tcpp101.zip" -OutFile "tcpp101.zip"
      - run: Expand-Archive -Path "tcpp101.zip" -DestinationPath "tcpp101" -Verbose
      - run: choco install 7zip.portable
      - run: cmd.exe -/c "7z x tcpp101\TCC.ZIP -otcpp101\tcc" 
      - run: $env:Path = (get-location).path + '\tcpp101\tcc;' + $env:Path
      - run: cmd.exe -/c "set PATH=%PATH%;%cd%\tcpp101\tcc && tree && echo %PATH% && build.bat"
