name: Build on Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: Invoke-WebRequest -Uri "https://web.archive.org/web/20060114221019if_/http://community.borland.com:80/article/images/21751/tcpp101.zip" -OutFile "tcpp101.zip"
      - run: Expand-Archive -Path "tcpp101.zip" -DestinationPath "tcpp101"
      - run: choco install 7zip.portable
      - run: cmd.exe -/c "7z x tcpp101\TCC.ZIP -otcpp101\tcc" 
      - run: Invoke-WebRequest -Uri https://github.com/otya128/winevdm/releases/download/v0.8.0/otvdm-v0.8.1.zip  -OutFile "otvdm.zip"
      - run: Expand-Archive -Path "otvdm.zip" -DestinationPath "otvdm"
      - run: pnputil -i -a otvdm\install.inf
      - run: cmd.exe -/c "tree && echo %cd% && echo %PATH% && build.bat"
