name: Build on Windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: Invoke-WebRequest -Uri "https://web.archive.org/web/20060114221019if_/http://community.borland.com:80/article/images/21751/tcpp101.zip" -OutFile "tcpp101.zip"
      - run: choco install 7zip.portable
      - run: cmd.exe -/c "7z x tcpp101.zip"
      - run: cmd.exe -/c "7z x tcpp101\TCC.ZIP"
      - run: $env:Path = (get-location).path + '\tcpp101\tcc;' + $env:Path
      - run: cmd.exe -/c "build.bat"
